<?php echo $this->doctype(); ?>

<html lang="en" ng-app="api-tools-api-first-admin">
    <head>
        <meta charset="utf-8">
<?php
    echo $this->headTitle('Laminas API First Application');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/img/favicon.ico')))
        ->appendStylesheet($this->basePath('/api-tools/css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('/api-tools/css/main.css'));
    echo $this->headScript()
        ->prependFile($this->basePath('/api-tools/js/bootstrap.min.js'))
        ->prependFile($this->basePath('/api-tools/js/jquery.min.js'));
?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top za1-nav">
            <div class="container">
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('/img/laminasapi_logo.png') ?>"></a>
                <ul class="nav navbar-nav">
                    <?php if (class_exists('Laminas\ApiTools\ApiFirstAdmin\Module', false)): ?>
                        <li class="active"><a href="<?php echo $this->basePath('/admin') ?>">Setup</a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>



        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Laminas Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
