<div class="hero-unit">
    <h1>Laminas API First Application</h1>
    <p>Hero image here</p>
</div>

<div class="row">
    <div class="span12">
        <h2>Getting Started</h2>
        <p>It it important that your application be put into development mode in order to start using the Laminas API First Administration screens to assist building your app.</p>
        <p>Currently, your application <b><?php echo (class_exists('Laminas\ApiTools\ApiFirstAdmin\Module', false)) ? 'IS' : 'IS NOT' ?></b> in development mode.  Here are some instructions on how to do it:</p>
    </div>
</div>
