<div class="hero-unit">
    <h1>Laminas API First Application</h1>
    <p>Hero image here</p>
</div>

<div class="row">
    <div class="span12">
        <h2>Getting Started</h2>
        <p>It it important that your application be put into development mode in order to start using the Laminas API First Administration screens to assist building your app.</p>
        <p>Currently, your application <b><?= (class_exists('Laminas\ApiTools\ApiFirstAdmin\Module', false)) ? 'IS' : 'IS NOT' ?></b> in development mode.  Here are some instructions on how to do it:</p>
    </div>

</div>

<!--<div class="row"> -->
<!-- -->
<!--    <div class="span4">-->
<!--        <h2>--><?php //echo $this->translate('Follow Development') ?><!--</h2>-->
<!--        <p>--><?php //echo sprintf($this->translate('Laminas is under active development. If you are interested in following the development of Laminas, there is a special Laminas portal on the official Laminas website which provides links to the Laminas %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="https://getlaminas.org/wiki/display/LaminasDEV2/Home">', '</a>', '<a href="https://getlaminas.org/laminas/blog">', '</a>', '<a href="https://github.com/laminas/laminas/issues">', '</a>') ?><!--</p>-->
<!--        <p><a class="btn btn-success" href="https://getlaminas.org/laminas" target="_blank">--><?php //echo $this->translate('Laminas Development Portal') ?><!-- &raquo;</a></p>-->
<!--    </div>-->
<!-- -->
<!--    <div class="span4">-->
<!--        <h2>--><?php //echo $this->translate('Discover Modules') ?><!--</h2>-->
<!--        <p>--><?php //echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for Laminas modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for Laminas.'), '<a href="https://github.com/laminas/modules.laminas.dev">', '</a>') ?><!--</p>-->
<!--        <p><a class="btn btn-success" href="http://modules.laminas.dev/" target="_blank">--><?php //echo $this->translate('Explore Laminas Modules') ?><!-- &raquo;</a></p>-->
<!--   </div>-->
<!-- -->
<!--   <div class="span4">-->
<!--       <h2>--><?php //echo $this->translate('Help &amp; Support') ?><!--</h2>-->
<!--       <p>--><?php //echo sprintf($this->translate('If you need any help or support while developing with Laminas, you may reach us via IRC: %s#laminastalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/laminastalk">', '</a>', '<a href="https://getlaminas.org/wiki/display/LaminasDEV/Mailing+Lists">', '</a>') ?><!--</p>-->
<!--       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=laminastalk" target="_blank">--><?php //echo $this->translate('Ping us on IRC') ?><!-- &raquo;</a></p>-->
<!--   </div>-->
<!--</div> -->
